name: Parse test

on: 
  push

jobs:
  build_AND_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ *.cpp 
      - name: Permission
        run: chmod +x run_test.sh
      - name: Run Test script
        run: ./run_test.sh a.out generated_output.txt
      - name: Upload result file
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: generated_output.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: Result
      - name: Check differences
        run: diff generated_output.txt good_output.txt